CREATE TABLE IF NOT EXISTS posts(
    `postID` CHAR(36) UNSIGNED PRIMARY KEY NOT NULL,
    `userID` CHAR(36) NOT NULL,
    `createdAt`TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    `description` TEXT NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID)
); 