name:  Run Unit Tests

on: [push]

jobs: 
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with: 
          go-version: '1.22.1'
    - name: Run Unit Tests
      run: make test